// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClothWEPAPI.Models
{
    public partial class AmountCategoriesResult
    {
        public string CategoriesName { get; set; }
        public int Amount { get; set; }
    }
}
