// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class Balance
    {
        public int StoreBalanceId { get; set; }
        public int CategoriesBalanceId { get; set; }
        public int Amount { get; set; }
        public DateTime? BalanceDate { get; set; }

        public virtual Category CategoriesBalance { get; set; }
        public virtual Store StoreBalance { get; set; }
    }
}