// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class Bill
    {
        public Bill()
        {
            DetailsBills = new HashSet<DetailsBill>();
        }

        public int BillId { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public int StoreId { get; set; }
        public string BillType { get; set; }
        public DateTime? PaymentDate { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<DetailsBill> DetailsBills { get; set; }
    }
}