// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class Category
    {
        public Category()
        {
            DetailsBills = new HashSet<DetailsBill>();
        }

        public int CategoriesId { get; set; }
        public string CategoriesName { get; set; }
        public decimal? CategoriesPrice { get; set; }
        public int UserId { get; set; }

        public virtual ICollection<DetailsBill> DetailsBills { get; set; }
    }
}