// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class Currency
    {
        public int CurrencyId { get; set; }
        public string CurrencyType { get; set; }
    }
}