// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class DetailsBill
    {
        public int DitailsId { get; set; }
        public decimal Price { get; set; }
        public int AmountPayment { get; set; }
        public int CategoriesId { get; set; }
        public int BillDitailsId { get; set; }

        public virtual Bill BillDitails { get; set; }
        public virtual Category Categories { get; set; }
    }
}