// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClothWEPAPI.Models
{
    public partial class GET_ALL_CUSTOMERSResult
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int? PhoneNumber { get; set; }
    }
}
