// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class Login
    {
        public int LoginId { get; set; }
        public string LoginUserName { get; set; }
        public string LoginPassword { get; set; }
        public int LoginRoleId { get; set; }
        public int LoginUserId { get; set; }

        public virtual Role LoginRole { get; set; }
        public virtual User LoginUser { get; set; }
    }
}