// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class Material
    {
        public int MaterialsId { get; set; }
        public string MaterialsName { get; set; }
        public decimal MaterialsPrice { get; set; }
        public int MaterialsAmount { get; set; }
    }
}