// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class Query1
    {
        public int CategoriesId { get; set; }
        public string CategoriesName { get; set; }
        public decimal? Expr1 { get; set; }
    }
}