// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class Store
    {
        public Store()
        {
            Bills = new HashSet<Bill>();
        }

        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string Street { get; set; }

        public virtual ICollection<Bill> Bills { get; set; }
    }
}