// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClothWEPAPI.Models
{
    public partial class View3
    {
        public string Name { get; set; }
        public int BillId { get; set; }
        public string BillType { get; set; }
        public string CategoriesName { get; set; }
    }
}