// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClothWEPAPI.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ClothWEPAPI.Data
{
    public partial interface IClothesDBContextProcedures
    {
        Task<int> ADDCATEGORIESAsync(int? ID, string NAME, decimal? PRICE, int? USERID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<AmountCategoriesResult>> AmountCategoriesAsync(string CategoriesName, string StoreName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> BackUpDBAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DELETECATEGORIESAsync(int? Cateid, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GET_ALL_CUSTOMERSResult>> GET_ALL_CUSTOMERSAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
